### ISSUE TITLE
Join forces with dirtbike?

### ISSUE THREAD

**Issue by ncoghlan** [fedora-python/rewheel#4]
Rather than collaborating with Fedora on rewheel, Debian created their own competing project in dirtbike: https://github.com/paulproteus/dirtbike

I've filed an issue over there asking what would be needed in order to join forces rather than continuing to duplicate effort needlessly: https://github.com/paulproteus/dirtbike/issues/23

This capability is a "necessary evil" in both cases, so maintaining both projects indefinitely seems like a bad idea.

**Comment by bkabrda** [comment]
+1, I just learned about dirtbike myself and wanted to propose that :)

**Comment by ncoghlan** [comment]
I suspect the "not an PyPI" may have had an impact, since dirtbike is pip installable, while AFAIK rewheel isn't :)

**Comment by bkabrda** [comment]
True, I never actually got around to publish it on PyPI and it remained the same when I transferred it to fedora-python...
Since I no longer have free time to invest in rewheel, I likely won't be able to contribute to this merging effort, but I would for sure love to see it happen.

**Comment by dstufft** [comment]
If I remember correctly, one of the things was that for Debian, they didn't want to actually **re**-wheel, because they don't use pip to install packages, so there isn't a `RECORD` file or anything. They generally have a `.egg-info` directory which... doesn't list the files by default or a `.egg-info` file which... never lists the files. So while I think dirtbike will discover all of the files if something was installed as wheel, they needed something that would integrate with `dpkg` to cover their common case of "we didn't actually record what files we installed in the Python metadata, only dpkg metadata".

**Comment by warsaw** [comment]
Hi!  Yes, apologies for rolling our own.  There were various (maybe good, maybe bad :smile:) reasons for it, but ~~rewheel~~ dirtbike is serving our immediate needs.  I think dirtbike _wants_ to be cross-distro so if you're up for it, collaboration to make it fill the needs of the F/RH ecosystem would be welcome.

**Comment by dstufft** [comment]
I think you mean that dirtbike is serving Debian's current immediate needs, right?

**Comment by warsaw** [comment]
Yep!

**Comment by ncoghlan** [comment]
Ironically, I would currently like to be able to pull the koji client libraries out of the system Python and into a venv (since koji is only shipped as an RPM), but rewheel can't help, since it relies on the Python level metadata, and if I had that, it would be because koji was already pip installable.

So a pluggable cross-distro dirtbike is likely a better general purpose solution, even though rewheel is still nice for the case where you're just wanting to base a venv package on the system provided version, rather than pull system-package-only content into a Python level development context.

**Comment by ncoghlan** [comment]
(That said, I'm also in a situation where granting the application venv access to the system site packages is an acceptable workaround, just an inelegant one)

**Comment by warsaw** [comment]
On Sep 05, 2016, at 12:44 AM, Nick Coghlan wrote:

> So a pluggable cross-distro dirtbike is likely a better general purpose
> solution

We would very much welcome patches to make dirtbike cross-distro.
